export const productData = [
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "22 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "20 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "22 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "20 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "22 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "20 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "22 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "20 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
    {
      name: "Sisyphus",
      url: "sisyphus.com",
      lastAssessed: "20 Jan 2022",
      licenseStatus: "Active",
      licenseType: "Customer data",
      userRole: "Admin",
    },
  ];